name: Deploy Website to K8s

on:
  push:
    branches:
      - main  # mainブランチにpushされたら起動

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]  # あなたが構築したLXC Runnerを指定
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f custom-site.yaml
